-- ============================================================
-- CQE NFT MONITORING PLATFORM - New Table DDL
-- Database : CQE_NFT (HANAINS1U)
-- Prefix   : API_NFT_  (all new tables)
-- Conventions follow existing API_AUTH_* tables:
--   CHAR(1) Y/N flags, SYSDATE defaults,
--   named constraints API_NFT_CHK_* / API_NFT_UK_*,
--   sequences for PKs, CLOB for large/HTML content
-- ============================================================

-- Safe drop (re-installable)
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
    'API_NFT_USER_LOB_ACCESS','API_NFT_APPD_CONFIG','API_NFT_KIBANA_CONFIG',
    'API_NFT_SPLUNK_CONFIG','API_NFT_MONGODB_CONFIG','API_NFT_PC_CONFIG',
    'API_NFT_DB_CONFIG','API_NFT_TRACK_TEMPLATE',
    'API_NFT_TEST_REGISTRATION','API_NFT_RELEASE_REPORTS'))
  LOOP EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS'; END LOOP;
END;
/
BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN (
    'API_NFT_KIBANA_SEQ','API_NFT_SPLUNK_SEQ','API_NFT_MONGODB_SEQ',
    'API_NFT_PC_CONFIG_SEQ','API_NFT_DB_CONFIG_SEQ','API_NFT_TRACK_SEQ',
    'API_NFT_REPORT_SEQ','API_NFT_TEST_REG_SEQ','API_NFT_APPD_CFG_SEQ'))
  LOOP EXECUTE IMMEDIATE 'DROP SEQUENCE '||s.sequence_name; END LOOP;
END;
/

-- ============================================================
-- SEQUENCES
-- ============================================================
CREATE SEQUENCE API_NFT_KIBANA_SEQ    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE API_NFT_SPLUNK_SEQ    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE API_NFT_MONGODB_SEQ   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE API_NFT_PC_CONFIG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE API_NFT_DB_CONFIG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE API_NFT_TRACK_SEQ     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE API_NFT_REPORT_SEQ    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE API_NFT_TEST_REG_SEQ  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE API_NFT_APPD_CFG_SEQ  START WITH 1 INCREMENT BY 1;

-- ============================================================
-- 1. USER LOB ACCESS
--    Maps API_AUTH_USERS to the LOBs they can access.
--    Admin manages; PE sees only assigned LOBs on login.
-- ============================================================
CREATE TABLE API_NFT_USER_LOB_ACCESS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME        VARCHAR2(100)  NOT NULL,   -- FK API_AUTH_USERS.USERNAME
    LOB_NAME        VARCHAR2(100)  NOT NULL,   -- FK API_LOB_MASTER.LOB_NAME
    GRANTED_BY      VARCHAR2(100)  NOT NULL,
    IS_ACTIVE       CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_DATE    DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_DATE    DATE           DEFAULT SYSDATE,
    CONSTRAINT API_NFT_CHK_ULA_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_UK_USER_LOB    UNIQUE (USERNAME, LOB_NAME)
);
COMMENT ON TABLE  API_NFT_USER_LOB_ACCESS IS 'Maps platform users to accessible LOBs';
COMMENT ON COLUMN API_NFT_USER_LOB_ACCESS.USERNAME IS 'References API_AUTH_USERS.USERNAME';
CREATE INDEX API_NFT_IDX_ULA_USER ON API_NFT_USER_LOB_ACCESS(USERNAME);
CREATE INDEX API_NFT_IDX_ULA_LOB  ON API_NFT_USER_LOB_ACCESS(LOB_NAME, IS_ACTIVE);

-- ============================================================
-- 2. APPD TOOL CONFIGURATION
--    Controller connection per LOB. Token via env var.
-- ============================================================
CREATE TABLE API_NFT_APPD_CONFIG (
    CONFIG_ID           NUMBER         DEFAULT API_NFT_APPD_CFG_SEQ.NEXTVAL PRIMARY KEY,
    LOB_NAME            VARCHAR2(100)  NOT NULL,
    CONTROLLER_URL      VARCHAR2(500)  NOT NULL,
    ACCOUNT_NAME        VARCHAR2(200)  NOT NULL,
    TOKEN_ENV_VAR       VARCHAR2(200)  NOT NULL,  -- e.g. APPD_TOKEN_CARDS
    DEFAULT_NODE_COUNT  NUMBER         DEFAULT 3,
    IS_ACTIVE           CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_BY          VARCHAR2(100),
    CREATED_DATE        DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_DATE        DATE           DEFAULT SYSDATE,
    CONSTRAINT API_NFT_CHK_APPD_ACT CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_UK_APPD_LOB  UNIQUE (LOB_NAME)
);
COMMENT ON TABLE  API_NFT_APPD_CONFIG IS 'AppDynamics controller config per LOB';
COMMENT ON COLUMN API_NFT_APPD_CONFIG.TOKEN_ENV_VAR IS 'Env var holding API token e.g. APPD_TOKEN_CARDS';
CREATE INDEX API_NFT_IDX_APPD_LOB ON API_NFT_APPD_CONFIG(LOB_NAME, IS_ACTIVE);

-- ============================================================
-- 3. KIBANA CONFIGURATION
--    One row per dashboard per LOB/Track.
--    display_name is user-defined name shown in UI.
-- ============================================================
CREATE TABLE API_NFT_KIBANA_CONFIG (
    KIBANA_CONFIG_ID  NUMBER         DEFAULT API_NFT_KIBANA_SEQ.NEXTVAL PRIMARY KEY,
    LOB_NAME          VARCHAR2(100)  NOT NULL,
    TRACK_NAME        VARCHAR2(100)  NOT NULL,
    KIBANA_URL        VARCHAR2(500)  NOT NULL,
    USERNAME          VARCHAR2(200),
    TOKEN_ENV_VAR     VARCHAR2(200)  NOT NULL,   -- e.g. KIBANA_TOKEN_CARDS
    AUTH_TYPE         VARCHAR2(20)   DEFAULT 'apikey' NOT NULL,  -- apikey | basic
    DASHBOARD_ID      VARCHAR2(200)  NOT NULL,
    DISPLAY_NAME      VARCHAR2(200)  NOT NULL,   -- User-defined e.g. API Performance CDV3
    INDEX_PATTERN     VARCHAR2(200),
    TIME_FIELD        VARCHAR2(100)  DEFAULT '@timestamp',
    IS_ACTIVE         CHAR(1)        DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS  VARCHAR2(20),              -- PASS | FAIL | NOT_TESTED
    LAST_TEST_DATE    DATE,
    CREATED_BY        VARCHAR2(100),
    CREATED_DATE      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY        VARCHAR2(100),
    UPDATED_DATE      DATE           DEFAULT SYSDATE,
    CONSTRAINT API_NFT_CHK_KIB_ACT    CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_CHK_KIB_AUTH   CHECK (AUTH_TYPE IN ('apikey','basic')),
    CONSTRAINT API_NFT_CHK_KIB_STATUS CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED') OR LAST_TEST_STATUS IS NULL),
    CONSTRAINT API_NFT_UK_KIB_DASH    UNIQUE (LOB_NAME, TRACK_NAME, DASHBOARD_ID)
);
COMMENT ON TABLE  API_NFT_KIBANA_CONFIG IS 'Kibana dashboard configs per LOB/Track';
COMMENT ON COLUMN API_NFT_KIBANA_CONFIG.DISPLAY_NAME  IS 'User-defined name shown in UI e.g. API Performance CDV3';
COMMENT ON COLUMN API_NFT_KIBANA_CONFIG.TOKEN_ENV_VAR IS 'Env var for auth token e.g. KIBANA_TOKEN_CARDS';
CREATE INDEX API_NFT_IDX_KIB_LOB ON API_NFT_KIBANA_CONFIG(LOB_NAME, TRACK_NAME, IS_ACTIVE);

-- ============================================================
-- 4. SPLUNK CONFIGURATION
--    Saved searches / dashboards per LOB/Track.
-- ============================================================
CREATE TABLE API_NFT_SPLUNK_CONFIG (
    SPLUNK_CONFIG_ID  NUMBER         DEFAULT API_NFT_SPLUNK_SEQ.NEXTVAL PRIMARY KEY,
    LOB_NAME          VARCHAR2(100)  NOT NULL,
    TRACK_NAME        VARCHAR2(100)  NOT NULL,
    SPLUNK_URL        VARCHAR2(500)  NOT NULL,
    TOKEN_ENV_VAR     VARCHAR2(200)  NOT NULL,   -- e.g. SPLUNK_TOKEN_CARDS
    DEFAULT_INDEX     VARCHAR2(200),
    SEARCH_NAME       VARCHAR2(200)  NOT NULL,   -- Saved search name or dashboard ID
    DISPLAY_NAME      VARCHAR2(200)  NOT NULL,
    SEARCH_TYPE       VARCHAR2(20)   DEFAULT 'search' NOT NULL,  -- search | dashboard
    SPL_QUERY         CLOB,                      -- SPL query for search type
    SEARCH_TIMEOUT_SEC NUMBER        DEFAULT 60,
    IS_ACTIVE         CHAR(1)        DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS  VARCHAR2(20),
    LAST_TEST_DATE    DATE,
    CREATED_BY        VARCHAR2(100),
    CREATED_DATE      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY        VARCHAR2(100),
    UPDATED_DATE      DATE           DEFAULT SYSDATE,
    CONSTRAINT API_NFT_CHK_SPL_ACT    CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_CHK_SPL_TYPE   CHECK (SEARCH_TYPE IN ('search','dashboard')),
    CONSTRAINT API_NFT_CHK_SPL_STATUS CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED') OR LAST_TEST_STATUS IS NULL),
    CONSTRAINT API_NFT_UK_SPL_SEARCH  UNIQUE (LOB_NAME, TRACK_NAME, SEARCH_NAME)
);
COMMENT ON TABLE  API_NFT_SPLUNK_CONFIG IS 'Splunk saved search/dashboard configs per LOB/Track';
COMMENT ON COLUMN API_NFT_SPLUNK_CONFIG.TOKEN_ENV_VAR IS 'Env var for HEC/API token e.g. SPLUNK_TOKEN_CARDS';
CREATE INDEX API_NFT_IDX_SPL_LOB ON API_NFT_SPLUNK_CONFIG(LOB_NAME, TRACK_NAME, IS_ACTIVE);

-- ============================================================
-- 5. MONGODB CONFIGURATION
--    Collection monitoring config per LOB/Track.
-- ============================================================
CREATE TABLE API_NFT_MONGODB_CONFIG (
    MONGODB_CONFIG_ID  NUMBER         DEFAULT API_NFT_MONGODB_SEQ.NEXTVAL PRIMARY KEY,
    LOB_NAME           VARCHAR2(100)  NOT NULL,
    TRACK_NAME         VARCHAR2(100)  NOT NULL,
    URI_ENV_VAR        VARCHAR2(200)  NOT NULL,   -- e.g. MONGO_URI_CARDS
    DATABASE_NAME      VARCHAR2(200)  NOT NULL,
    COLLECTION_NAME    VARCHAR2(200)  NOT NULL,
    DISPLAY_NAME       VARCHAR2(200)  NOT NULL,
    AUTH_DATABASE      VARCHAR2(100)  DEFAULT 'admin',
    USERNAME           VARCHAR2(200),
    PASS_ENV_VAR       VARCHAR2(200),             -- e.g. MONGO_PASS_CARDS
    REPLICA_SET        VARCHAR2(100),
    SLOW_QUERY_MS      NUMBER         DEFAULT 100,
    READ_PREFERENCE    VARCHAR2(50)   DEFAULT 'primaryPreferred',
    CONNECTION_TIMEOUT NUMBER         DEFAULT 5000,
    IS_ACTIVE          CHAR(1)        DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS   VARCHAR2(20),
    LAST_TEST_DATE     DATE,
    CREATED_BY         VARCHAR2(100),
    CREATED_DATE       DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY         VARCHAR2(100),
    UPDATED_DATE       DATE           DEFAULT SYSDATE,
    CONSTRAINT API_NFT_CHK_MDB_ACT    CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_CHK_MDB_STATUS CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED') OR LAST_TEST_STATUS IS NULL),
    CONSTRAINT API_NFT_UK_MDB_COLL    UNIQUE (LOB_NAME, TRACK_NAME, DATABASE_NAME, COLLECTION_NAME)
);
COMMENT ON TABLE  API_NFT_MONGODB_CONFIG IS 'MongoDB collection monitoring configs per LOB/Track';
COMMENT ON COLUMN API_NFT_MONGODB_CONFIG.URI_ENV_VAR  IS 'Env var for MongoDB URI e.g. MONGO_URI_CARDS';
COMMENT ON COLUMN API_NFT_MONGODB_CONFIG.PASS_ENV_VAR IS 'Env var for MongoDB password e.g. MONGO_PASS_CARDS';
CREATE INDEX API_NFT_IDX_MDB_LOB ON API_NFT_MONGODB_CONFIG(LOB_NAME, TRACK_NAME, IS_ACTIVE);

-- ============================================================
-- 6. PERFORMANCE CENTER CONFIGURATION
--    PC 24.1 project config per LOB/Track.
-- ============================================================
CREATE TABLE API_NFT_PC_CONFIG (
    PC_CONFIG_ID      NUMBER         DEFAULT API_NFT_PC_CONFIG_SEQ.NEXTVAL PRIMARY KEY,
    LOB_NAME          VARCHAR2(100)  NOT NULL,
    TRACK_NAME        VARCHAR2(100)  NOT NULL,
    PC_URL            VARCHAR2(500)  NOT NULL,
    PC_PORT           NUMBER         DEFAULT 443,
    USERNAME          VARCHAR2(200)  NOT NULL,
    PASS_ENV_VAR      VARCHAR2(200)  NOT NULL,    -- e.g. PC_PASS_CARDS
    DOMAIN            VARCHAR2(100)  DEFAULT 'DEFAULT',
    PROJECT_NAME      VARCHAR2(200)  NOT NULL,
    DISPLAY_NAME      VARCHAR2(200)  NOT NULL,
    DURATION_FORMAT   VARCHAR2(20)   DEFAULT 'HM',   -- HM | SECONDS (PC 24.1 = HM)
    COOKIE_FLAG       VARCHAR2(10)   DEFAULT '-b',   -- Required for PC 24.1 report dl
    REPORT_TIMEOUT_SEC NUMBER        DEFAULT 300,
    IS_ACTIVE         CHAR(1)        DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS  VARCHAR2(20),
    LAST_TEST_DATE    DATE,
    LAST_RUN_ID       VARCHAR2(100),
    CREATED_BY        VARCHAR2(100),
    CREATED_DATE      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY        VARCHAR2(100),
    UPDATED_DATE      DATE           DEFAULT SYSDATE,
    CONSTRAINT API_NFT_CHK_PC_ACT      CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_CHK_PC_DURATION CHECK (DURATION_FORMAT IN ('HM','SECONDS')),
    CONSTRAINT API_NFT_CHK_PC_STATUS   CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED') OR LAST_TEST_STATUS IS NULL),
    CONSTRAINT API_NFT_UK_PC_PROJECT   UNIQUE (LOB_NAME, TRACK_NAME, PROJECT_NAME)
);
COMMENT ON TABLE  API_NFT_PC_CONFIG IS 'Performance Center project configs per LOB/Track (PC 24.1)';
COMMENT ON COLUMN API_NFT_PC_CONFIG.PASS_ENV_VAR     IS 'Env var for PC password e.g. PC_PASS_CARDS';
COMMENT ON COLUMN API_NFT_PC_CONFIG.DURATION_FORMAT  IS 'PC 24.1 requires HM (Hours/Minutes), not SECONDS';
COMMENT ON COLUMN API_NFT_PC_CONFIG.COOKIE_FLAG      IS '-b flag required for PC 24.1 report downloads';
CREATE INDEX API_NFT_IDX_PC_LOB ON API_NFT_PC_CONFIG(LOB_NAME, TRACK_NAME, IS_ACTIVE);

-- ============================================================
-- 7. DATABASE CONFIGURATION
--    Oracle DB host/port/service per LOB. Passwords via env vars.
-- ============================================================
CREATE TABLE API_NFT_DB_CONFIG (
    DB_CONFIG_ID      NUMBER         DEFAULT API_NFT_DB_CONFIG_SEQ.NEXTVAL PRIMARY KEY,
    LOB_NAME          VARCHAR2(100)  NOT NULL,
    DISPLAY_NAME      VARCHAR2(200)  NOT NULL,    -- e.g. CQE_NFT
    DB_TYPE           VARCHAR2(50)   DEFAULT 'Oracle' NOT NULL,
    HOST              VARCHAR2(500)  NOT NULL,
    PORT              NUMBER         DEFAULT 1521 NOT NULL,
    SERVICE_NAME      VARCHAR2(200)  NOT NULL,
    USERNAME          VARCHAR2(200)  NOT NULL,
    PASS_ENV_VAR      VARCHAR2(200)  NOT NULL,    -- e.g. DB_PASS_CQE_NFT
    USE_CYBERARK      CHAR(1)        DEFAULT 'N' NOT NULL,
    CYBERARK_SAFE     VARCHAR2(200),
    CYBERARK_OBJECT   VARCHAR2(200),
    ALLOWED_OPERATIONS VARCHAR2(50)  DEFAULT 'DQL',  -- DQL | DML | DQL,DML
    IS_ACTIVE         CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_BY        VARCHAR2(100),
    CREATED_DATE      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY        VARCHAR2(100),
    UPDATED_DATE      DATE           DEFAULT SYSDATE,
    CONSTRAINT API_NFT_CHK_DB_ACT      CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_CHK_DB_CYBERARK CHECK (USE_CYBERARK IN ('Y','N')),
    CONSTRAINT API_NFT_UK_DB_LOB_NAME  UNIQUE (LOB_NAME, DISPLAY_NAME)
);
COMMENT ON TABLE  API_NFT_DB_CONFIG IS 'Oracle DB configs per LOB. Passwords via env vars only - never stored.';
COMMENT ON COLUMN API_NFT_DB_CONFIG.PASS_ENV_VAR IS 'Env var holding password e.g. DB_PASS_CQE_NFT';
CREATE INDEX API_NFT_IDX_DB_LOB ON API_NFT_DB_CONFIG(LOB_NAME, IS_ACTIVE);

-- ============================================================
-- 8. TRACK TEMPLATE
--    Maps all tool configs to a LOB/Track.
--    This is the master template PE loads at monitoring start.
--    IDs are comma-separated FKs to respective config tables.
-- ============================================================
CREATE TABLE API_NFT_TRACK_TEMPLATE (
    TEMPLATE_ID        NUMBER         DEFAULT API_NFT_TRACK_SEQ.NEXTVAL PRIMARY KEY,
    LOB_NAME           VARCHAR2(100)  NOT NULL,
    TRACK_NAME         VARCHAR2(100)  NOT NULL,
    -- Comma-separated IDs from config tables
    APPD_APP_IDS       VARCHAR2(4000),  -- APP_MASTER_IDs from APPD_APPLICATIONS_MASTER
    KIBANA_CONFIG_IDS  VARCHAR2(1000),  -- KIBANA_CONFIG_IDs from API_NFT_KIBANA_CONFIG
    SPLUNK_CONFIG_IDS  VARCHAR2(1000),  -- SPLUNK_CONFIG_IDs from API_NFT_SPLUNK_CONFIG
    MONGODB_CONFIG_IDS VARCHAR2(1000),  -- MONGODB_CONFIG_IDs from API_NFT_MONGODB_CONFIG
    PC_CONFIG_IDS      VARCHAR2(1000),  -- PC_CONFIG_IDs from API_NFT_PC_CONFIG
    DB_CONFIG_IDS      VARCHAR2(1000),  -- DB_CONFIG_IDs from API_NFT_DB_CONFIG
    -- Summary counts for fast UI display
    APPD_APP_COUNT     NUMBER         DEFAULT 0,
    KIBANA_COUNT       NUMBER         DEFAULT 0,
    SPLUNK_COUNT       NUMBER         DEFAULT 0,
    MONGODB_COUNT      NUMBER         DEFAULT 0,
    PC_COUNT           NUMBER         DEFAULT 0,
    DB_COUNT           NUMBER         DEFAULT 0,
    IS_ACTIVE          CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_BY         VARCHAR2(100),
    CREATED_DATE       DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY         VARCHAR2(100),
    UPDATED_DATE       DATE           DEFAULT SYSDATE,
    CONSTRAINT API_NFT_CHK_TMPL_ACT CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_UK_TRACK_TMPL UNIQUE (LOB_NAME, TRACK_NAME)
);
COMMENT ON TABLE  API_NFT_TRACK_TEMPLATE IS 'Master template mapping all tool configs to a LOB/Track';
COMMENT ON COLUMN API_NFT_TRACK_TEMPLATE.APPD_APP_IDS IS 'Comma-separated APP_MASTER_IDs from APPD_APPLICATIONS_MASTER';
COMMENT ON COLUMN API_NFT_TRACK_TEMPLATE.KIBANA_CONFIG_IDS IS 'Comma-separated KIBANA_CONFIG_IDs from API_NFT_KIBANA_CONFIG';
CREATE INDEX API_NFT_IDX_TMPL_LOB ON API_NFT_TRACK_TEMPLATE(LOB_NAME, TRACK_NAME, IS_ACTIVE);

-- ============================================================
-- 9. TEST REGISTRATION
--    Records each NFT test registered by PE.
--    Must be created before monitoring starts.
--    Links to API_RUN_MASTER via RUN_ID.
-- ============================================================
CREATE TABLE API_NFT_TEST_REGISTRATION (
    REG_ID               NUMBER         DEFAULT API_NFT_TEST_REG_SEQ.NEXTVAL PRIMARY KEY,
    RUN_ID               VARCHAR2(100)  NOT NULL,  -- FK API_RUN_MASTER.RUN_ID
    PC_RUN_ID            VARCHAR2(50)   NOT NULL,
    LOB_NAME             VARCHAR2(100)  NOT NULL,
    TRACK_NAME           VARCHAR2(100)  NOT NULL,
    TEST_NAME            VARCHAR2(200)  NOT NULL,
    TEST_TYPE            VARCHAR2(50),             -- LOAD|STRESS|ENDURANCE|SPIKE|SOAK
    ENVIRONMENT          VARCHAR2(50)   DEFAULT 'PERF',
    RELEASE_NAME         VARCHAR2(200),
    PEAK_VUSERS          NUMBER,
    RAMP_UP_MINUTES      NUMBER,
    PLANNED_DURATION_HRS NUMBER,
    JENKINS_BUILD        VARCHAR2(100),
    TEMPLATE_ID          NUMBER,                   -- FK API_NFT_TRACK_TEMPLATE.TEMPLATE_ID
    REGISTERED_BY        VARCHAR2(100)  NOT NULL,
    REGISTRATION_DATE    DATE           DEFAULT SYSDATE NOT NULL,
    NOTES                VARCHAR2(2000),
    CONSTRAINT API_NFT_CHK_REG_TYPE CHECK (
        TEST_TYPE IN ('LOAD','STRESS','ENDURANCE','SPIKE','SOAK') OR TEST_TYPE IS NULL),
    CONSTRAINT API_NFT_UK_REG_RUN UNIQUE (RUN_ID),
    CONSTRAINT API_NFT_UK_REG_PC  UNIQUE (PC_RUN_ID)
);
COMMENT ON TABLE  API_NFT_TEST_REGISTRATION IS 'Test registration - must exist before monitoring can start';
COMMENT ON COLUMN API_NFT_TEST_REGISTRATION.RUN_ID IS 'Generated by RunIDGenerator - FK to API_RUN_MASTER.RUN_ID';
CREATE INDEX API_NFT_IDX_REG_LOB     ON API_NFT_TEST_REGISTRATION(LOB_NAME, TRACK_NAME);
CREATE INDEX API_NFT_IDX_REG_DATE    ON API_NFT_TEST_REGISTRATION(REGISTRATION_DATE DESC);
CREATE INDEX API_NFT_IDX_REG_RELEASE ON API_NFT_TEST_REGISTRATION(RELEASE_NAME, LOB_NAME);

-- ============================================================
-- 10. RELEASE REPORTS
--     Full HTML stored as CLOB. Retained 12+ months.
--     Only LOAD / STRESS / ENDURANCE final results.
-- ============================================================
CREATE TABLE API_NFT_RELEASE_REPORTS (
    REPORT_ID           NUMBER         DEFAULT API_NFT_REPORT_SEQ.NEXTVAL PRIMARY KEY,
    RUN_ID              VARCHAR2(100)  NOT NULL,   -- FK API_RUN_MASTER.RUN_ID
    PC_RUN_ID           VARCHAR2(50)   NOT NULL,
    LOB_NAME            VARCHAR2(100)  NOT NULL,
    RELEASE_NAME        VARCHAR2(200)  NOT NULL,
    TEST_TYPE           VARCHAR2(50)   NOT NULL,   -- LOAD|STRESS|ENDURANCE
    TEST_NAME           VARCHAR2(200),
    TRACK_NAME          VARCHAR2(100),
    REPORT_HTML         CLOB           NOT NULL,   -- Complete page HTML
    REPORT_SIZE_KB      NUMBER,
    OVERALL_STATUS      VARCHAR2(20),              -- PASS|FAIL|PARTIAL
    PASS_RATE_PCT       NUMBER,
    PEAK_VUSERS         NUMBER,
    AVG_RESPONSE_MS     NUMBER,
    P95_RESPONSE_MS     NUMBER,
    TOTAL_TRANSACTIONS  NUMBER,
    FAILED_TRANSACTIONS NUMBER,
    RETAIN_UNTIL        DATE,                      -- NULL = keep indefinitely
    IS_ACTIVE           CHAR(1)        DEFAULT 'Y' NOT NULL,
    SAVED_BY            VARCHAR2(100)  NOT NULL,
    SAVED_DATE          DATE           DEFAULT SYSDATE NOT NULL,
    NOTES               VARCHAR2(2000),
    CONSTRAINT API_NFT_CHK_RPT_ACT    CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT API_NFT_CHK_RPT_TYPE   CHECK (TEST_TYPE IN ('LOAD','STRESS','ENDURANCE')),
    CONSTRAINT API_NFT_CHK_RPT_STATUS CHECK (OVERALL_STATUS IN ('PASS','FAIL','PARTIAL') OR OVERALL_STATUS IS NULL),
    CONSTRAINT API_NFT_UK_RPT_RUN     UNIQUE (RUN_ID, TEST_TYPE)
);
COMMENT ON TABLE  API_NFT_RELEASE_REPORTS IS 'Final test report HTML as CLOB. 12+ month retention.';
COMMENT ON COLUMN API_NFT_RELEASE_REPORTS.REPORT_HTML IS 'Full HTML of test-report.html for long-term viewing via UI';
COMMENT ON COLUMN API_NFT_RELEASE_REPORTS.RETAIN_UNTIL IS 'NULL = retain indefinitely. Regular test data tables cleaned periodically.';
CREATE INDEX API_NFT_IDX_RPT_LOB  ON API_NFT_RELEASE_REPORTS(LOB_NAME, RELEASE_NAME);
CREATE INDEX API_NFT_IDX_RPT_DATE ON API_NFT_RELEASE_REPORTS(SAVED_DATE DESC);
CREATE INDEX API_NFT_IDX_RPT_TYPE ON API_NFT_RELEASE_REPORTS(TEST_TYPE, IS_ACTIVE);

-- ============================================================
-- GRANT PERMISSIONS (uncomment and set your_app_user)
-- ============================================================
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_USER_LOB_ACCESS  TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_APPD_CONFIG       TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_KIBANA_CONFIG     TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_SPLUNK_CONFIG     TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_MONGODB_CONFIG    TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_PC_CONFIG         TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_DB_CONFIG         TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_TRACK_TEMPLATE    TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_TEST_REGISTRATION TO your_app_user;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON API_NFT_RELEASE_REPORTS   TO your_app_user;
-- GRANT SELECT,UPDATE ON API_NFT_KIBANA_SEQ,API_NFT_SPLUNK_SEQ,API_NFT_MONGODB_SEQ TO your_app_user;
-- GRANT SELECT,UPDATE ON API_NFT_PC_CONFIG_SEQ,API_NFT_DB_CONFIG_SEQ               TO your_app_user;
-- GRANT SELECT,UPDATE ON API_NFT_TRACK_SEQ,API_NFT_REPORT_SEQ,API_NFT_TEST_REG_SEQ TO your_app_user;
-- GRANT SELECT,UPDATE ON API_NFT_APPD_CFG_SEQ                                       TO your_app_user;

-- Verify
SELECT table_name FROM user_tables WHERE table_name LIKE 'API_NFT_%' ORDER BY table_name;
COMMIT;
