-- ==========================================
-- UPDATED Database Schema with TRACK Support
-- ==========================================

-- Drop existing table if needed (careful - this deletes data!)
-- DROP TABLE APPD_APPLICATIONS_MASTER CASCADE CONSTRAINTS;
-- DROP SEQUENCE APPD_APP_MASTER_SEQ;

-- Create Applications Master Table with TRACK column
CREATE TABLE APPD_APPLICATIONS_MASTER (
    APP_MASTER_ID NUMBER PRIMARY KEY,
    APPLICATION_NAME VARCHAR2(200) NOT NULL,
    LOB_NAME VARCHAR2(100) NOT NULL,
    TRACK VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT CHK_APP_MASTER_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT UQ_APP_LOB_TRACK UNIQUE (APPLICATION_NAME, LOB_NAME, TRACK)
);

CREATE SEQUENCE APPD_APP_MASTER_SEQ START WITH 1 INCREMENT BY 1;

-- Create indexes for better performance
CREATE INDEX IDX_APP_MASTER_LOB ON APPD_APPLICATIONS_MASTER(LOB_NAME);
CREATE INDEX IDX_APP_MASTER_TRACK ON APPD_APPLICATIONS_MASTER(TRACK);
CREATE INDEX IDX_APP_MASTER_LOB_TRACK ON APPD_APPLICATIONS_MASTER(LOB_NAME, TRACK);

COMMENT ON TABLE APPD_APPLICATIONS_MASTER IS 'Master list of AppDynamics applications with LOB and Track';
COMMENT ON COLUMN APPD_APPLICATIONS_MASTER.TRACK IS 'Track/Release identifier (e.g., CDV3, Q1_2026)';

-- Insert Sample Applications for Digital Technology
INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'icg-tts-paymentinitiation-pte-173720_PTE', 'Digital Technology', 'CDV3', 'Payment Initiation Service - CDV3', 'Y');

INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'icg-tts-authservice-pte-173721_PTE', 'Digital Technology', 'CDV3', 'Auth Service - CDV3', 'Y');

INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'icg-tts-dataplatform-pte-173722_PTE', 'Digital Technology', 'CDV4', 'Data Platform - CDV4', 'Y');

-- Insert Sample Applications for Retail
INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'RetailWeb', 'Retail', 'Q1_2026', 'Retail Web Application - Q1', 'Y');

INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'RetailAPI', 'Retail', 'Q1_2026', 'Retail API Service - Q1', 'Y');

INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'RetailMobile', 'Retail', 'Q2_2026', 'Retail Mobile App - Q2', 'Y');

-- Insert Sample Applications for Data
INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'DataPlatform', 'Data', 'V1.0', 'Data Platform Service', 'Y');

INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'DataAnalytics', 'Data', 'V1.0', 'Data Analytics Engine', 'Y');

-- Insert Sample Applications for Payments
INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'PaymentGateway', 'Payments', 'R2026.1', 'Payment Gateway', 'Y');

INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'PaymentProcessor', 'Payments', 'R2026.1', 'Payment Processor', 'Y');

-- Insert Sample Applications for Commercial Cards
INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'CommercialCardsAPI', 'Commercial Cards', 'Sprint23', 'Commercial Cards API', 'Y');

INSERT INTO APPD_APPLICATIONS_MASTER (APP_MASTER_ID, APPLICATION_NAME, LOB_NAME, TRACK, DESCRIPTION, IS_ACTIVE)
VALUES (APPD_APP_MASTER_SEQ.NEXTVAL, 'CommercialCardsWeb', 'Commercial Cards', 'Sprint23', 'Commercial Cards Web Portal', 'Y');

COMMIT;

-- Verify the data
SELECT LOB_NAME, TRACK, COUNT(*) AS APP_COUNT
FROM APPD_APPLICATIONS_MASTER
WHERE IS_ACTIVE = 'Y'
GROUP BY LOB_NAME, TRACK
ORDER BY LOB_NAME, TRACK;