-- =============================================================================
-- API_KIBANA_METRICS — Kibana endpoint metrics per monitoring run
-- Run this in SQL Developer against CQE_NFT schema
-- =============================================================================

CREATE SEQUENCE API_KIBANA_METRICS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE API_KIBANA_METRICS (
    METRIC_ID               NUMBER          NOT NULL,
    RUN_ID                  VARCHAR2(100)   NOT NULL,
    DASHBOARD_ID            VARCHAR2(200)   NOT NULL,
    DASHBOARD_NAME          VARCHAR2(300),
    API_ENDPOINT            VARCHAR2(500),
    API_NAME                VARCHAR2(500),
    COLLECTION_TIME         TIMESTAMP(6)    DEFAULT SYSTIMESTAMP,

    -- Volume metrics
    TOTAL_REQUESTS          NUMBER(15, 0)   DEFAULT 0,
    TOTAL_COUNT             NUMBER(15, 0)   DEFAULT 0,
    PASS_COUNT              NUMBER(15, 0)   DEFAULT 0,
    FAIL_COUNT              NUMBER(15, 0)   DEFAULT 0,

    -- Response time metrics (milliseconds)
    MIN_RESPONSE_TIME_MS    NUMBER(10, 2)   DEFAULT 0,
    AVG_RESPONSE_TIME_MS    NUMBER(10, 2)   DEFAULT 0,
    MAX_RESPONSE_TIME_MS    NUMBER(10, 2)   DEFAULT 0,
    P90_RESPONSE_TIME_MS    NUMBER(10, 2)   DEFAULT 0,
    P95_RESPONSE_TIME_MS    NUMBER(10, 2)   DEFAULT 0,

    -- Extended data
    ADDITIONAL_METRICS      CLOB,
    CREATED_DATE            DATE            DEFAULT SYSDATE,

    CONSTRAINT API_KIBANA_METRICS_PK PRIMARY KEY (METRIC_ID),
    CONSTRAINT API_KIBANA_METRICS_RUN_FK FOREIGN KEY (RUN_ID)
        REFERENCES API_RUN_MASTER(RUN_ID)
)
LOB (ADDITIONAL_METRICS) STORE AS BASICFILE (ENABLE STORAGE IN ROW);

CREATE INDEX IDX_KIBANA_METRICS_RUN ON API_KIBANA_METRICS(RUN_ID);
CREATE INDEX IDX_KIBANA_METRICS_DASH ON API_KIBANA_METRICS(DASHBOARD_ID);
CREATE INDEX IDX_KIBANA_METRICS_TIME ON API_KIBANA_METRICS(COLLECTION_TIME);

COMMENT ON TABLE  API_KIBANA_METRICS IS 'Kibana API endpoint metrics collected during NFT monitoring runs';
COMMENT ON COLUMN API_KIBANA_METRICS.RUN_ID IS 'FK to API_RUN_MASTER.RUN_ID';
COMMENT ON COLUMN API_KIBANA_METRICS.DASHBOARD_ID IS 'Kibana dashboard UUID';
COMMENT ON COLUMN API_KIBANA_METRICS.API_ENDPOINT IS 'Endpoint URI from Kibana index (userRequestedUri.keyword)';
COMMENT ON COLUMN API_KIBANA_METRICS.PASS_COUNT IS 'Requests with finalStatus/resCodeFromCP/resCodeToClient 200-299';
COMMENT ON COLUMN API_KIBANA_METRICS.ADDITIONAL_METRICS IS 'JSON blob with raw percentiles and extra fields';

COMMIT;
