-- =============================================================================
-- CQE NFT Monitoring Platform - New Table DDL
-- Compatible with existing: API_AUTH_*, API_LOB_MASTER, API_RUN_MASTER,
--   API_APPD_*, API_AWR_*, API_PC_*, API_LR_*
-- Naming: API_NFT_* prefix  |  CHAR(1) Y/N flags  |  SYSDATE defaults
-- Passwords/tokens stored as ENV VAR NAMES only - never plain text
-- =============================================================================

-- Drop in child-first order (safe re-install)
DROP TABLE API_NFT_RELEASE_REPORTS   CASCADE CONSTRAINTS PURGE;
DROP TABLE API_NFT_TRACK_TEMPLATE    CASCADE CONSTRAINTS PURGE;
DROP TABLE API_NFT_KIBANA_CONFIG     CASCADE CONSTRAINTS PURGE;
DROP TABLE API_NFT_SPLUNK_CONFIG     CASCADE CONSTRAINTS PURGE;
DROP TABLE API_NFT_MONGODB_CONFIG    CASCADE CONSTRAINTS PURGE;
DROP TABLE API_NFT_PC_CONFIG         CASCADE CONSTRAINTS PURGE;
DROP TABLE API_NFT_DB_CONFIG         CASCADE CONSTRAINTS PURGE;
DROP TABLE API_NFT_APPD_CONFIG       CASCADE CONSTRAINTS PURGE;
DROP TABLE API_NFT_USER_LOB_ACCESS   CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE API_NFT_USER_LOB_SEQ;
DROP SEQUENCE API_NFT_APPD_CFG_SEQ;
DROP SEQUENCE API_NFT_KIBANA_CFG_SEQ;
DROP SEQUENCE API_NFT_SPLUNK_CFG_SEQ;
DROP SEQUENCE API_NFT_MONGODB_CFG_SEQ;
DROP SEQUENCE API_NFT_PC_CFG_SEQ;
DROP SEQUENCE API_NFT_DB_CFG_SEQ;
DROP SEQUENCE API_NFT_TRACK_TPL_SEQ;
DROP SEQUENCE API_NFT_REPORT_SEQ;
COMMIT;

-- =============================================================================
-- 1. SEQUENCES
-- =============================================================================
CREATE SEQUENCE API_NFT_USER_LOB_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE API_NFT_APPD_CFG_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE API_NFT_KIBANA_CFG_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE API_NFT_SPLUNK_CFG_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE API_NFT_MONGODB_CFG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE API_NFT_PC_CFG_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE API_NFT_DB_CFG_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE API_NFT_TRACK_TPL_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE API_NFT_REPORT_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =============================================================================
-- 2. API_NFT_USER_LOB_ACCESS
--    Maps API_AUTH_USERS to the LOBs they can access
--    Used by PE/test_lead login to show only their assigned LOBs
-- =============================================================================
CREATE TABLE API_NFT_USER_LOB_ACCESS (
    ACCESS_ID       NUMBER          NOT NULL,
    USERNAME        VARCHAR2(100)   NOT NULL,
    LOB_NAME        VARCHAR2(100)   NOT NULL,
    GRANTED_BY      VARCHAR2(100)   NOT NULL,
    GRANTED_DATE    DATE            DEFAULT SYSDATE NOT NULL,
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' NOT NULL,
    REVOKED_BY      VARCHAR2(100),
    REVOKED_DATE    DATE,
    CONSTRAINT PK_NFT_USER_LOB      PRIMARY KEY (ACCESS_ID),
    CONSTRAINT UK_NFT_USER_LOB      UNIQUE (USERNAME, LOB_NAME),
    CONSTRAINT CHK_NFT_ULA_ACTIVE   CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT FK_NFT_ULA_USER      FOREIGN KEY (USERNAME)
        REFERENCES API_AUTH_USERS(USERNAME) ON DELETE CASCADE
);
COMMENT ON TABLE  API_NFT_USER_LOB_ACCESS IS
    'Maps users to accessible LOBs - admin grants access for PE/test_lead roles';
COMMENT ON COLUMN API_NFT_USER_LOB_ACCESS.IS_ACTIVE IS 'Y=active, N=revoked';
CREATE INDEX IDX_NFT_ULA_USERNAME ON API_NFT_USER_LOB_ACCESS(USERNAME);
CREATE INDEX IDX_NFT_ULA_LOB      ON API_NFT_USER_LOB_ACCESS(LOB_NAME);
CREATE INDEX IDX_NFT_ULA_ACTIVE   ON API_NFT_USER_LOB_ACCESS(IS_ACTIVE);

-- =============================================================================
-- 3. API_NFT_APPD_CONFIG
--    AppDynamics controller config per LOB/Track
--    TOKEN_ENV_VAR stores the env variable NAME, never the actual token
-- =============================================================================
CREATE TABLE API_NFT_APPD_CONFIG (
    CONFIG_ID           NUMBER          NOT NULL,
    LOB_NAME            VARCHAR2(100)   NOT NULL,
    TRACK               VARCHAR2(50)    NOT NULL,
    CONTROLLER_URL      VARCHAR2(500)   NOT NULL,
    ACCOUNT_NAME        VARCHAR2(200)   NOT NULL,
    TOKEN_ENV_VAR       VARCHAR2(200)   NOT NULL,
    APPLICATION_NAMES   VARCHAR2(2000),
    TIER_FILTER         VARCHAR2(1000),
    NODE_FILTER         VARCHAR2(1000),
    COLLECTION_INTERVAL NUMBER          DEFAULT 300,
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS    VARCHAR2(20)    DEFAULT 'NOT_TESTED',
    LAST_TEST_DATE      DATE,
    CREATED_BY          VARCHAR2(100)   NOT NULL,
    CREATED_DATE        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_DATE        DATE,
    CONSTRAINT PK_NFT_APPD_CFG      PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UK_NFT_APPD_LOB_TRK  UNIQUE (LOB_NAME, TRACK),
    CONSTRAINT CHK_NFT_APPD_ACTIVE  CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_NFT_APPD_STATUS  CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED'))
);
COMMENT ON TABLE  API_NFT_APPD_CONFIG IS
    'AppDynamics controller config per LOB/Track - tokens via env var only';
COMMENT ON COLUMN API_NFT_APPD_CONFIG.TOKEN_ENV_VAR IS
    'Env variable name holding actual API token - e.g. APPD_TOKEN_RETAIL_CDV3';
CREATE INDEX IDX_NFT_APPD_LOB    ON API_NFT_APPD_CONFIG(LOB_NAME);
CREATE INDEX IDX_NFT_APPD_ACTIVE ON API_NFT_APPD_CONFIG(IS_ACTIVE);

-- =============================================================================
-- 4. API_NFT_KIBANA_CONFIG
--    Kibana dashboard config per LOB/Track
-- =============================================================================
CREATE TABLE API_NFT_KIBANA_CONFIG (
    CONFIG_ID           NUMBER          NOT NULL,
    LOB_NAME            VARCHAR2(100)   NOT NULL,
    TRACK               VARCHAR2(50)    NOT NULL,
    KIBANA_URL          VARCHAR2(500)   NOT NULL,
    DASHBOARD_ID        VARCHAR2(200),
    DISPLAY_NAME        VARCHAR2(200),
    INDEX_PATTERN       VARCHAR2(200),
    TOKEN_ENV_VAR       VARCHAR2(200),
    TIME_FIELD          VARCHAR2(100)   DEFAULT '@timestamp',
    DEFAULT_TIME_RANGE  VARCHAR2(50)    DEFAULT 'last_1h',
    CUSTOM_FILTERS      VARCHAR2(2000),
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS    VARCHAR2(20)    DEFAULT 'NOT_TESTED',
    LAST_TEST_DATE      DATE,
    CREATED_BY          VARCHAR2(100)   NOT NULL,
    CREATED_DATE        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_DATE        DATE,
    CONSTRAINT PK_NFT_KIB_CFG      PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UK_NFT_KIB_LOB_TRK  UNIQUE (LOB_NAME, TRACK),
    CONSTRAINT CHK_NFT_KIB_ACTIVE  CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_NFT_KIB_STATUS  CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED'))
);
COMMENT ON TABLE  API_NFT_KIBANA_CONFIG IS 'Kibana dashboard config per LOB/Track';
COMMENT ON COLUMN API_NFT_KIBANA_CONFIG.TOKEN_ENV_VAR IS
    'Env var name for Kibana API token - never store token directly';
CREATE INDEX IDX_NFT_KIB_LOB    ON API_NFT_KIBANA_CONFIG(LOB_NAME);
CREATE INDEX IDX_NFT_KIB_ACTIVE ON API_NFT_KIBANA_CONFIG(IS_ACTIVE);

-- =============================================================================
-- 5. API_NFT_SPLUNK_CONFIG
--    Splunk saved search / dashboard config per LOB/Track
-- =============================================================================
CREATE TABLE API_NFT_SPLUNK_CONFIG (
    CONFIG_ID           NUMBER          NOT NULL,
    LOB_NAME            VARCHAR2(100)   NOT NULL,
    TRACK               VARCHAR2(50)    NOT NULL,
    SPLUNK_URL          VARCHAR2(500)   NOT NULL,
    TOKEN_ENV_VAR       VARCHAR2(200)   NOT NULL,
    DEFAULT_INDEX       VARCHAR2(200),
    SAVED_SEARCH_NAME   VARCHAR2(200),
    SPL_QUERY           CLOB,
    SEARCH_TYPE         VARCHAR2(20)    DEFAULT 'search',
    DASHBOARD_NAME      VARCHAR2(200),
    TIME_RANGE          VARCHAR2(50)    DEFAULT '-1h',
    ERROR_PATTERNS      VARCHAR2(2000),
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS    VARCHAR2(20)    DEFAULT 'NOT_TESTED',
    LAST_TEST_DATE      DATE,
    CREATED_BY          VARCHAR2(100)   NOT NULL,
    CREATED_DATE        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_DATE        DATE,
    CONSTRAINT PK_NFT_SPL_CFG      PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UK_NFT_SPL_LOB_TRK  UNIQUE (LOB_NAME, TRACK),
    CONSTRAINT CHK_NFT_SPL_ACTIVE  CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_NFT_SPL_TYPE    CHECK (SEARCH_TYPE IN ('search','dashboard')),
    CONSTRAINT CHK_NFT_SPL_STATUS  CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED'))
);
COMMENT ON TABLE  API_NFT_SPLUNK_CONFIG IS 'Splunk saved search/dashboard config per LOB/Track';
COMMENT ON COLUMN API_NFT_SPLUNK_CONFIG.TOKEN_ENV_VAR IS 'Env var name for Splunk API token';
COMMENT ON COLUMN API_NFT_SPLUNK_CONFIG.SPL_QUERY     IS 'Full SPL query - stored as CLOB';
CREATE INDEX IDX_NFT_SPL_LOB    ON API_NFT_SPLUNK_CONFIG(LOB_NAME);
CREATE INDEX IDX_NFT_SPL_ACTIVE ON API_NFT_SPLUNK_CONFIG(IS_ACTIVE);

-- =============================================================================
-- 6. API_NFT_MONGODB_CONFIG
--    MongoDB monitoring config per LOB/Track - URI via env var only
-- =============================================================================
CREATE TABLE API_NFT_MONGODB_CONFIG (
    CONFIG_ID           NUMBER          NOT NULL,
    LOB_NAME            VARCHAR2(100)   NOT NULL,
    TRACK               VARCHAR2(50)    NOT NULL,
    URI_ENV_VAR         VARCHAR2(200)   NOT NULL,
    DATABASE_NAME       VARCHAR2(200)   NOT NULL,
    COLLECTION_NAMES    VARCHAR2(2000),
    REPLICA_SET         VARCHAR2(200),
    AUTH_DB             VARCHAR2(100)   DEFAULT 'admin',
    SLOW_QUERY_MS       NUMBER          DEFAULT 100,
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS    VARCHAR2(20)    DEFAULT 'NOT_TESTED',
    LAST_TEST_DATE      DATE,
    CREATED_BY          VARCHAR2(100)   NOT NULL,
    CREATED_DATE        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_DATE        DATE,
    CONSTRAINT PK_NFT_MDB_CFG      PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UK_NFT_MDB_LOB_TRK  UNIQUE (LOB_NAME, TRACK),
    CONSTRAINT CHK_NFT_MDB_ACTIVE  CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_NFT_MDB_STATUS  CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED'))
);
COMMENT ON TABLE  API_NFT_MONGODB_CONFIG IS 'MongoDB monitoring config per LOB/Track - URI via env var';
COMMENT ON COLUMN API_NFT_MONGODB_CONFIG.URI_ENV_VAR IS
    'Env var name for MongoDB connection URI - never store URI directly';
CREATE INDEX IDX_NFT_MDB_LOB    ON API_NFT_MONGODB_CONFIG(LOB_NAME);
CREATE INDEX IDX_NFT_MDB_ACTIVE ON API_NFT_MONGODB_CONFIG(IS_ACTIVE);

-- =============================================================================
-- 7. API_NFT_PC_CONFIG
--    Performance Center project config per LOB/Track
-- =============================================================================
CREATE TABLE API_NFT_PC_CONFIG (
    CONFIG_ID           NUMBER          NOT NULL,
    LOB_NAME            VARCHAR2(100)   NOT NULL,
    TRACK               VARCHAR2(50)    NOT NULL,
    PC_URL              VARCHAR2(500)   NOT NULL,
    PC_DOMAIN           VARCHAR2(200)   NOT NULL,
    PC_PROJECT          VARCHAR2(200)   NOT NULL,
    USERNAME            VARCHAR2(200)   NOT NULL,
    PASSWORD_ENV_VAR    VARCHAR2(200)   NOT NULL,
    DURATION_FORMAT     VARCHAR2(10)    DEFAULT 'HM',
    COOKIE_FLAG         VARCHAR2(10)    DEFAULT '-b',
    DEFAULT_TIMEOUT_MIN NUMBER          DEFAULT 120,
    LAST_RUN_ID         VARCHAR2(100),
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS    VARCHAR2(20)    DEFAULT 'NOT_TESTED',
    LAST_TEST_DATE      DATE,
    CREATED_BY          VARCHAR2(100)   NOT NULL,
    CREATED_DATE        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_DATE        DATE,
    CONSTRAINT PK_NFT_PC_CFG        PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UK_NFT_PC_LOB_TRK    UNIQUE (LOB_NAME, TRACK),
    CONSTRAINT CHK_NFT_PC_ACTIVE    CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_NFT_PC_DURATION  CHECK (DURATION_FORMAT IN ('HM','SECONDS')),
    CONSTRAINT CHK_NFT_PC_STATUS    CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED'))
);
COMMENT ON TABLE  API_NFT_PC_CONFIG IS 'Performance Center project config per LOB/Track';
COMMENT ON COLUMN API_NFT_PC_CONFIG.PASSWORD_ENV_VAR IS
    'Env var name for PC password - never store password directly';
COMMENT ON COLUMN API_NFT_PC_CONFIG.DURATION_FORMAT  IS
    'HM=Hours+Minutes, SECONDS=total seconds - PC 24.1 quirk';
COMMENT ON COLUMN API_NFT_PC_CONFIG.COOKIE_FLAG      IS
    'curl -b flag required for PC 24.1 report download';
CREATE INDEX IDX_NFT_PC_LOB    ON API_NFT_PC_CONFIG(LOB_NAME);
CREATE INDEX IDX_NFT_PC_ACTIVE ON API_NFT_PC_CONFIG(IS_ACTIVE);

-- =============================================================================
-- 8. API_NFT_DB_CONFIG
--    Oracle DB configs for AWR target databases per LOB/Track
-- =============================================================================
CREATE TABLE API_NFT_DB_CONFIG (
    CONFIG_ID           NUMBER          NOT NULL,
    LOB_NAME            VARCHAR2(100)   NOT NULL,
    TRACK               VARCHAR2(50)    NOT NULL,
    DB_ALIAS            VARCHAR2(100)   NOT NULL,
    HOST                VARCHAR2(200)   NOT NULL,
    PORT                NUMBER          DEFAULT 1521 NOT NULL,
    SERVICE_NAME        VARCHAR2(200)   NOT NULL,
    USERNAME            VARCHAR2(200)   NOT NULL,
    PASSWORD_ENV_VAR    VARCHAR2(200)   NOT NULL,
    USE_CYBERARK        CHAR(1)         DEFAULT 'N' NOT NULL,
    CYBERARK_SAFE       VARCHAR2(200),
    CYBERARK_OBJECT     VARCHAR2(200),
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
    LAST_TEST_STATUS    VARCHAR2(20)    DEFAULT 'NOT_TESTED',
    LAST_TEST_DATE      DATE,
    CREATED_BY          VARCHAR2(100)   NOT NULL,
    CREATED_DATE        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_DATE        DATE,
    CONSTRAINT PK_NFT_DB_CFG        PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UK_NFT_DB_LOB_TRK    UNIQUE (LOB_NAME, TRACK),
    CONSTRAINT CHK_NFT_DB_ACTIVE    CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_NFT_DB_CYBERARK  CHECK (USE_CYBERARK IN ('Y','N')),
    CONSTRAINT CHK_NFT_DB_STATUS    CHECK (LAST_TEST_STATUS IN ('PASS','FAIL','NOT_TESTED'))
);
COMMENT ON TABLE  API_NFT_DB_CONFIG IS 'Oracle DB config for AWR target DBs per LOB/Track';
COMMENT ON COLUMN API_NFT_DB_CONFIG.PASSWORD_ENV_VAR IS
    'Env var name for DB password - never store password directly';
COMMENT ON COLUMN API_NFT_DB_CONFIG.USE_CYBERARK IS
    'Y=fetch password from CyberArk, N=use env var';
CREATE INDEX IDX_NFT_DB_LOB    ON API_NFT_DB_CONFIG(LOB_NAME);
CREATE INDEX IDX_NFT_DB_ACTIVE ON API_NFT_DB_CONFIG(IS_ACTIVE);

-- =============================================================================
-- 9. API_NFT_TRACK_TEMPLATE
--    Central track profile - links LOB+Track to all tool config IDs
-- =============================================================================
CREATE TABLE API_NFT_TRACK_TEMPLATE (
    TEMPLATE_ID         NUMBER          NOT NULL,
    LOB_NAME            VARCHAR2(100)   NOT NULL,
    TRACK               VARCHAR2(50)    NOT NULL,
    APPD_CONFIG_IDS     VARCHAR2(500),
    KIBANA_CONFIG_IDS   VARCHAR2(500),
    SPLUNK_CONFIG_IDS   VARCHAR2(500),
    MONGODB_CONFIG_IDS  VARCHAR2(500),
    PC_CONFIG_IDS       VARCHAR2(500),
    DB_CONFIG_IDS       VARCHAR2(500),
    APPD_COUNT          NUMBER          DEFAULT 0,
    KIBANA_COUNT        NUMBER          DEFAULT 0,
    SPLUNK_COUNT        NUMBER          DEFAULT 0,
    MONGODB_COUNT       NUMBER          DEFAULT 0,
    PC_COUNT            NUMBER          DEFAULT 0,
    DB_COUNT            NUMBER          DEFAULT 0,
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_BY          VARCHAR2(100)   NOT NULL,
    CREATED_DATE        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_DATE        DATE,
    CONSTRAINT PK_NFT_TRACK_TPL    PRIMARY KEY (TEMPLATE_ID),
    CONSTRAINT UK_NFT_TPL_LOB_TRK  UNIQUE (LOB_NAME, TRACK),
    CONSTRAINT CHK_NFT_TPL_ACTIVE  CHECK (IS_ACTIVE IN ('Y','N'))
);
COMMENT ON TABLE  API_NFT_TRACK_TEMPLATE IS
    'Central track profile - links LOB+Track to all tool configs';
COMMENT ON COLUMN API_NFT_TRACK_TEMPLATE.APPD_CONFIG_IDS IS
    'Comma-sep CONFIG_IDs from API_NFT_APPD_CONFIG';
CREATE INDEX IDX_NFT_TPL_LOB    ON API_NFT_TRACK_TEMPLATE(LOB_NAME);
CREATE INDEX IDX_NFT_TPL_ACTIVE ON API_NFT_TRACK_TEMPLATE(IS_ACTIVE);

-- =============================================================================
-- 10. API_NFT_RELEASE_REPORTS
--     Final test report HTML stored as CLOB - 12+ month retention
-- =============================================================================
CREATE TABLE API_NFT_RELEASE_REPORTS (
    REPORT_ID       NUMBER          NOT NULL,
    RUN_ID          VARCHAR2(100)   NOT NULL,
    LOB_NAME        VARCHAR2(100)   NOT NULL,
    TRACK           VARCHAR2(50),
    TEST_NAME       VARCHAR2(200),
    TEST_TYPE       VARCHAR2(50),
    PC_RUN_ID       VARCHAR2(50),
    REPORT_TITLE    VARCHAR2(500),
    REPORT_HTML     CLOB,
    REPORT_SIZE_KB  NUMBER,
    GENERATED_BY    VARCHAR2(100),
    GENERATED_DATE  DATE            DEFAULT SYSDATE NOT NULL,
    RETAIN_UNTIL    DATE,
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' NOT NULL,
    NOTES           VARCHAR2(2000),
    CONSTRAINT PK_NFT_REPORT       PRIMARY KEY (REPORT_ID),
    CONSTRAINT UK_NFT_REPORT_RUN   UNIQUE (RUN_ID),
    CONSTRAINT CHK_NFT_RPT_ACTIVE  CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_NFT_RPT_TYPE    CHECK (
        TEST_TYPE IN ('LOAD','STRESS','ENDURANCE','SPIKE','SOAK')
        OR TEST_TYPE IS NULL),
    CONSTRAINT FK_NFT_RPT_RUN      FOREIGN KEY (RUN_ID)
        REFERENCES API_RUN_MASTER(RUN_ID)
);
COMMENT ON TABLE  API_NFT_RELEASE_REPORTS IS
    'Final test report HTML CLOB - 12+ month retention policy';
COMMENT ON COLUMN API_NFT_RELEASE_REPORTS.REPORT_HTML  IS
    'Complete HTML report including all tool data and AI RCA';
COMMENT ON COLUMN API_NFT_RELEASE_REPORTS.RETAIN_UNTIL IS
    'NULL=keep forever, date=auto-cleanup eligible after this date';
CREATE INDEX IDX_NFT_RPT_LOB    ON API_NFT_RELEASE_REPORTS(LOB_NAME);
CREATE INDEX IDX_NFT_RPT_RUN    ON API_NFT_RELEASE_REPORTS(RUN_ID);
CREATE INDEX IDX_NFT_RPT_DATE   ON API_NFT_RELEASE_REPORTS(GENERATED_DATE);
CREATE INDEX IDX_NFT_RPT_ACTIVE ON API_NFT_RELEASE_REPORTS(IS_ACTIVE);

COMMIT;

-- =============================================================================
-- VERIFICATION
-- =============================================================================
SELECT TABLE_NAME, NUM_ROWS
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'API_NFT_%'
ORDER BY TABLE_NAME;

SELECT SEQUENCE_NAME
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME LIKE 'API_NFT_%'
ORDER BY SEQUENCE_NAME;
