-- =====================================================
-- AppDynamics Monitoring Database Schema
-- Complete schema for LOB-based monitoring
-- =====================================================

-- =====================================================
-- 1. LOB Configuration Table
-- =====================================================
CREATE TABLE APPD_LOB_CONFIG (
    LOB_ID NUMBER PRIMARY KEY,
    LOB_NAME VARCHAR2(100) NOT NULL UNIQUE,
    LOB_DESCRIPTION VARCHAR2(500),
    APPLICATION_NAMES CLOB,  -- JSON array of AppD application names
    LAST_DISCOVERY_RUN DATE,
    DISCOVERY_SCHEDULE VARCHAR2(50) DEFAULT 'DAILY',  -- DAILY, WEEKLY, etc.
    IS_ACTIVE VARCHAR2(1) DEFAULT 'Y',
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT CHK_APPD_LOB_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE APPD_LOB_CONFIG_SEQ START WITH 1;
CREATE INDEX IDX_APPD_LOB_NAME ON APPD_LOB_CONFIG(LOB_NAME);

-- Sample LOB data
-- INSERT INTO APPD_LOB_CONFIG (LOB_ID, LOB_NAME, LOB_DESCRIPTION, APPLICATION_NAMES)
-- VALUES (APPD_LOB_CONFIG_SEQ.NEXTVAL, 'Retail', 'Retail Applications', '["RetailWeb", "RetailAPI", "RetailMobile"]');


-- =====================================================
-- 2. Application Discovery Table
-- Stores discovered applications with active/inactive status
-- =====================================================
CREATE TABLE APPD_APPLICATIONS (
    APP_ID NUMBER PRIMARY KEY,
    LOB_ID NUMBER NOT NULL,
    APPLICATION_NAME VARCHAR2(200) NOT NULL,
    APPLICATION_ID VARCHAR2(100),  -- AppD internal ID
    TOTAL_TIERS NUMBER DEFAULT 0,
    TOTAL_NODES NUMBER DEFAULT 0,
    ACTIVE_NODES NUMBER DEFAULT 0,
    INACTIVE_NODES NUMBER DEFAULT 0,
    DISCOVERY_DATE DATE DEFAULT SYSDATE,
    LAST_SEEN_DATE DATE,
    IS_ACTIVE VARCHAR2(1) DEFAULT 'Y',
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_APPD_APP_LOB FOREIGN KEY (LOB_ID) REFERENCES APPD_LOB_CONFIG(LOB_ID),
    CONSTRAINT CHK_APPD_APP_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE APPD_APPLICATIONS_SEQ START WITH 1;
CREATE INDEX IDX_APPD_APP_LOB ON APPD_APPLICATIONS(LOB_ID);
CREATE INDEX IDX_APPD_APP_NAME ON APPD_APPLICATIONS(APPLICATION_NAME);
CREATE UNIQUE INDEX UDX_APPD_APP_LOB_NAME ON APPD_APPLICATIONS(LOB_ID, APPLICATION_NAME);


-- =====================================================
-- 3. Tier Discovery Table
-- Stores all tiers within applications
-- =====================================================
CREATE TABLE APPD_TIERS (
    TIER_ID NUMBER PRIMARY KEY,
    APP_ID NUMBER NOT NULL,
    TIER_NAME VARCHAR2(200) NOT NULL,
    TIER_ID_APPD VARCHAR2(100),  -- AppD internal tier ID
    TIER_TYPE VARCHAR2(100),  -- Java, .NET, PHP, etc.
    TOTAL_NODES NUMBER DEFAULT 0,
    ACTIVE_NODES NUMBER DEFAULT 0,
    IS_ACTIVE VARCHAR2(1) DEFAULT 'Y',
    LAST_SEEN_DATE DATE,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_APPD_TIER_APP FOREIGN KEY (APP_ID) REFERENCES APPD_APPLICATIONS(APP_ID),
    CONSTRAINT CHK_APPD_TIER_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE APPD_TIERS_SEQ START WITH 1;
CREATE INDEX IDX_APPD_TIER_APP ON APPD_TIERS(APP_ID);
CREATE INDEX IDX_APPD_TIER_NAME ON APPD_TIERS(TIER_NAME);
CREATE UNIQUE INDEX UDX_APPD_TIER_APP_NAME ON APPD_TIERS(APP_ID, TIER_NAME);


-- =====================================================
-- 4. Node Discovery Table
-- Stores all nodes with active/inactive status based on CPM
-- =====================================================
CREATE TABLE APPD_NODES (
    NODE_ID NUMBER PRIMARY KEY,
    TIER_ID NUMBER NOT NULL,
    APP_ID NUMBER NOT NULL,
    NODE_NAME VARCHAR2(200) NOT NULL,
    NODE_ID_APPD VARCHAR2(100),  -- AppD internal node ID
    MACHINE_NAME VARCHAR2(200),
    IP_ADDRESS VARCHAR2(50),
    
    -- Activity metrics for classification
    CALLS_PER_MINUTE NUMBER DEFAULT 0,
    LAST_ACTIVITY_TIME TIMESTAMP,
    
    -- Classification
    IS_ACTIVE VARCHAR2(1) DEFAULT 'Y',  -- Based on CPM > threshold
    ACTIVE_THRESHOLD NUMBER DEFAULT 10,  -- Minimum CPM to be considered active
    
    -- Metadata
    NODE_TYPE VARCHAR2(100),  -- Java, .NET, etc.
    AGENT_VERSION VARCHAR2(50),
    
    LAST_SEEN_DATE DATE,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_APPD_NODE_TIER FOREIGN KEY (TIER_ID) REFERENCES APPD_TIERS(TIER_ID),
    CONSTRAINT FK_APPD_NODE_APP FOREIGN KEY (APP_ID) REFERENCES APPD_APPLICATIONS(APP_ID),
    CONSTRAINT CHK_APPD_NODE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE APPD_NODES_SEQ START WITH 1;
CREATE INDEX IDX_APPD_NODE_TIER ON APPD_NODES(TIER_ID);
CREATE INDEX IDX_APPD_NODE_APP ON APPD_NODES(APP_ID);
CREATE INDEX IDX_APPD_NODE_ACTIVE ON APPD_NODES(IS_ACTIVE);
CREATE UNIQUE INDEX UDX_APPD_NODE_TIER_NAME ON APPD_NODES(TIER_ID, NODE_NAME);


-- =====================================================
-- 5. Monitoring Runs Table
-- Tracks each monitoring session
-- =====================================================
CREATE TABLE APPD_MONITORING_RUNS (
    RUN_ID VARCHAR2(200) PRIMARY KEY,
    LOB_ID NUMBER NOT NULL,
    LOB_NAME VARCHAR2(100),
    TRACK VARCHAR2(100),
    TEST_NAME VARCHAR2(200),
    
    -- Session details
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    STATUS VARCHAR2(50) DEFAULT 'RUNNING',  -- RUNNING, COMPLETED, STOPPED, FAILED
    
    -- Configuration
    COLLECTION_INTERVAL_SECONDS NUMBER DEFAULT 1800,
    APPLICATIONS CLOB,  -- JSON array of application names
    
    -- Statistics
    TOTAL_COLLECTIONS NUMBER DEFAULT 0,
    SUCCESSFUL_COLLECTIONS NUMBER DEFAULT 0,
    FAILED_COLLECTIONS NUMBER DEFAULT 0,
    LAST_COLLECTION_TIME TIMESTAMP,
    
    -- Error tracking
    ERROR_MESSAGE VARCHAR2(4000),
    
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_APPD_RUN_LOB FOREIGN KEY (LOB_ID) REFERENCES APPD_LOB_CONFIG(LOB_ID),
    CONSTRAINT CHK_APPD_RUN_STATUS CHECK (STATUS IN ('RUNNING', 'COMPLETED', 'STOPPED', 'FAILED'))
);

CREATE INDEX IDX_APPD_RUN_LOB ON APPD_MONITORING_RUNS(LOB_ID);
CREATE INDEX IDX_APPD_RUN_STATUS ON APPD_MONITORING_RUNS(STATUS);
CREATE INDEX IDX_APPD_RUN_START ON APPD_MONITORING_RUNS(START_TIME);


-- =====================================================
-- 6. Server Metrics Table
-- Stores CPU, Memory, Network, Disk metrics
-- =====================================================
CREATE TABLE APPD_SERVER_METRICS (
    METRIC_ID NUMBER PRIMARY KEY,
    RUN_ID VARCHAR2(200) NOT NULL,
    NODE_ID NUMBER NOT NULL,
    COLLECTION_TIME TIMESTAMP NOT NULL,
    
    -- CPU Metrics
    CPU_BUSY_PERCENT NUMBER(5,2),
    CPU_IDLE_PERCENT NUMBER(5,2),
    CPU_STOLEN_PERCENT NUMBER(5,2),
    
    -- Memory Metrics
    MEMORY_TOTAL_MB NUMBER,
    MEMORY_USED_MB NUMBER,
    MEMORY_FREE_MB NUMBER,
    MEMORY_USED_PERCENT NUMBER(5,2),
    
    -- Network Metrics
    NETWORK_INCOMING_KB NUMBER,
    NETWORK_OUTGOING_KB NUMBER,
    
    -- Disk Metrics
    DISK_READS_PER_SEC NUMBER,
    DISK_WRITES_PER_SEC NUMBER,
    DISK_USED_PERCENT NUMBER(5,2),
    DISK_QUEUE_LENGTH NUMBER,
    
    -- Additional metrics as JSON
    ADDITIONAL_METRICS CLOB,
    
    CREATED_DATE DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_APPD_SERVER_RUN FOREIGN KEY (RUN_ID) REFERENCES APPD_MONITORING_RUNS(RUN_ID),
    CONSTRAINT FK_APPD_SERVER_NODE FOREIGN KEY (NODE_ID) REFERENCES APPD_NODES(NODE_ID)
);

CREATE SEQUENCE APPD_SERVER_METRICS_SEQ START WITH 1;
CREATE INDEX IDX_APPD_SERVER_RUN ON APPD_SERVER_METRICS(RUN_ID);
CREATE INDEX IDX_APPD_SERVER_NODE ON APPD_SERVER_METRICS(NODE_ID);
CREATE INDEX IDX_APPD_SERVER_TIME ON APPD_SERVER_METRICS(COLLECTION_TIME);


-- =====================================================
-- 7. JVM Metrics Table
-- Stores Heap, GC, Thread, Exception metrics
-- =====================================================
CREATE TABLE APPD_JVM_METRICS (
    METRIC_ID NUMBER PRIMARY KEY,
    RUN_ID VARCHAR2(200) NOT NULL,
    NODE_ID NUMBER NOT NULL,
    COLLECTION_TIME TIMESTAMP NOT NULL,
    
    -- Heap Metrics
    HEAP_USED_MB NUMBER,
    HEAP_COMMITTED_MB NUMBER,
    HEAP_MAX_MB NUMBER,
    HEAP_USED_PERCENT NUMBER(5,2),
    
    -- Non-Heap Metrics
    NON_HEAP_USED_MB NUMBER,
    NON_HEAP_COMMITTED_MB NUMBER,
    
    -- GC Metrics
    GC_TIME_MS NUMBER,
    GC_MAJOR_COLLECTION_COUNT NUMBER,
    GC_MINOR_COLLECTION_COUNT NUMBER,
    GC_TIME_SPENT_PERCENT NUMBER(5,2),
    
    -- Thread Metrics
    THREAD_COUNT NUMBER,
    THREAD_CURRENT NUMBER,
    THREAD_PEAK NUMBER,
    THREAD_DAEMON NUMBER,
    THREAD_BLOCKED NUMBER,
    
    -- Exception/Error Metrics
    EXCEPTION_COUNT NUMBER DEFAULT 0,
    ERROR_COUNT NUMBER DEFAULT 0,
    
    -- Call Metrics
    SLOW_CALLS_COUNT NUMBER DEFAULT 0,
    VERY_SLOW_CALLS_COUNT NUMBER DEFAULT 0,
    STALL_CALLS_COUNT NUMBER DEFAULT 0,
    
    -- Class Metrics
    CLASSES_LOADED NUMBER,
    CLASSES_UNLOADED NUMBER,
    
    -- Additional metrics as JSON
    ADDITIONAL_METRICS CLOB,
    
    CREATED_DATE DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_APPD_JVM_RUN FOREIGN KEY (RUN_ID) REFERENCES APPD_MONITORING_RUNS(RUN_ID),
    CONSTRAINT FK_APPD_JVM_NODE FOREIGN KEY (NODE_ID) REFERENCES APPD_NODES(NODE_ID)
);

CREATE SEQUENCE APPD_JVM_METRICS_SEQ START WITH 1;
CREATE INDEX IDX_APPD_JVM_RUN ON APPD_JVM_METRICS(RUN_ID);
CREATE INDEX IDX_APPD_JVM_NODE ON APPD_JVM_METRICS(NODE_ID);
CREATE INDEX IDX_APPD_JVM_TIME ON APPD_JVM_METRICS(COLLECTION_TIME);


-- =====================================================
-- 8. Application Metrics Table
-- Stores Calls per minute, Response time, Errors
-- =====================================================
CREATE TABLE APPD_APPLICATION_METRICS (
    METRIC_ID NUMBER PRIMARY KEY,
    RUN_ID VARCHAR2(200) NOT NULL,
    NODE_ID NUMBER NOT NULL,
    TIER_ID NUMBER NOT NULL,
    APP_ID NUMBER NOT NULL,
    COLLECTION_TIME TIMESTAMP NOT NULL,
    
    -- Call Metrics
    CALLS_PER_MINUTE NUMBER DEFAULT 0,
    CALLS_TOTAL NUMBER DEFAULT 0,
    
    -- Response Time Metrics
    RESPONSE_TIME_AVG_MS NUMBER,
    RESPONSE_TIME_MIN_MS NUMBER,
    RESPONSE_TIME_MAX_MS NUMBER,
    RESPONSE_TIME_P90_MS NUMBER,
    RESPONSE_TIME_P95_MS NUMBER,
    RESPONSE_TIME_P99_MS NUMBER,
    
    -- Error Metrics
    ERRORS_PER_MINUTE NUMBER DEFAULT 0,
    ERROR_RATE_PERCENT NUMBER(5,2) DEFAULT 0,
    ERRORS_TOTAL NUMBER DEFAULT 0,
    
    -- Business Transaction Metrics
    BT_NORMAL_COUNT NUMBER DEFAULT 0,
    BT_SLOW_COUNT NUMBER DEFAULT 0,
    BT_VERY_SLOW_COUNT NUMBER DEFAULT 0,
    BT_STALLED_COUNT NUMBER DEFAULT 0,
    BT_ERROR_COUNT NUMBER DEFAULT 0,
    
    -- Performance Indicators
    APDEX_SCORE NUMBER(3,2),
    
    -- Additional metrics as JSON
    ADDITIONAL_METRICS CLOB,
    
    CREATED_DATE DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_APPD_APP_METRIC_RUN FOREIGN KEY (RUN_ID) REFERENCES APPD_MONITORING_RUNS(RUN_ID),
    CONSTRAINT FK_APPD_APP_METRIC_NODE FOREIGN KEY (NODE_ID) REFERENCES APPD_NODES(NODE_ID),
    CONSTRAINT FK_APPD_APP_METRIC_TIER FOREIGN KEY (TIER_ID) REFERENCES APPD_TIERS(TIER_ID),
    CONSTRAINT FK_APPD_APP_METRIC_APP FOREIGN KEY (APP_ID) REFERENCES APPD_APPLICATIONS(APP_ID)
);

CREATE SEQUENCE APPD_APP_METRICS_SEQ START WITH 1;
CREATE INDEX IDX_APPD_APP_METRIC_RUN ON APPD_APPLICATION_METRICS(RUN_ID);
CREATE INDEX IDX_APPD_APP_METRIC_NODE ON APPD_APPLICATION_METRICS(NODE_ID);
CREATE INDEX IDX_APPD_APP_METRIC_TIME ON APPD_APPLICATION_METRICS(COLLECTION_TIME);


-- =====================================================
-- 9. Discovery Audit Log
-- Tracks discovery runs for compliance
-- =====================================================
CREATE TABLE APPD_DISCOVERY_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    LOB_ID NUMBER,
    DISCOVERY_START_TIME TIMESTAMP NOT NULL,
    DISCOVERY_END_TIME TIMESTAMP,
    STATUS VARCHAR2(50),  -- SUCCESS, FAILED, PARTIAL
    APPLICATIONS_DISCOVERED NUMBER DEFAULT 0,
    TIERS_DISCOVERED NUMBER DEFAULT 0,
    NODES_DISCOVERED NUMBER DEFAULT 0,
    ACTIVE_NODES_COUNT NUMBER DEFAULT 0,
    ERROR_MESSAGE VARCHAR2(4000),
    EXECUTION_TIME_SECONDS NUMBER,
    CREATED_DATE DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_APPD_DISC_LOG_LOB FOREIGN KEY (LOB_ID) REFERENCES APPD_LOB_CONFIG(LOB_ID)
);

CREATE SEQUENCE APPD_DISCOVERY_LOG_SEQ START WITH 1;
CREATE INDEX IDX_APPD_DISC_LOB ON APPD_DISCOVERY_LOG(LOB_ID);
CREATE INDEX IDX_APPD_DISC_TIME ON APPD_DISCOVERY_LOG(DISCOVERY_START_TIME);


-- =====================================================
-- Helpful Views
-- =====================================================

-- View: Active nodes per LOB
CREATE OR REPLACE VIEW VW_APPD_ACTIVE_NODES_BY_LOB AS
SELECT 
    l.LOB_NAME,
    a.APPLICATION_NAME,
    t.TIER_NAME,
    n.NODE_NAME,
    n.CALLS_PER_MINUTE,
    n.IS_ACTIVE,
    n.LAST_ACTIVITY_TIME
FROM APPD_LOB_CONFIG l
JOIN APPD_APPLICATIONS a ON l.LOB_ID = a.LOB_ID
JOIN APPD_TIERS t ON a.APP_ID = t.APP_ID
JOIN APPD_NODES n ON t.TIER_ID = n.TIER_ID
WHERE n.IS_ACTIVE = 'Y'
ORDER BY l.LOB_NAME, a.APPLICATION_NAME, t.TIER_NAME, n.NODE_NAME;


-- View: LOB Summary Statistics
CREATE OR REPLACE VIEW VW_APPD_LOB_SUMMARY AS
SELECT 
    l.LOB_ID,
    l.LOB_NAME,
    COUNT(DISTINCT a.APP_ID) as TOTAL_APPLICATIONS,
    COUNT(DISTINCT t.TIER_ID) as TOTAL_TIERS,
    COUNT(n.NODE_ID) as TOTAL_NODES,
    SUM(CASE WHEN n.IS_ACTIVE = 'Y' THEN 1 ELSE 0 END) as ACTIVE_NODES,
    SUM(CASE WHEN n.IS_ACTIVE = 'N' THEN 1 ELSE 0 END) as INACTIVE_NODES,
    l.LAST_DISCOVERY_RUN
FROM APPD_LOB_CONFIG l
LEFT JOIN APPD_APPLICATIONS a ON l.LOB_ID = a.LOB_ID
LEFT JOIN APPD_TIERS t ON a.APP_ID = t.APP_ID
LEFT JOIN APPD_NODES n ON t.TIER_ID = n.TIER_ID
GROUP BY l.LOB_ID, l.LOB_NAME, l.LAST_DISCOVERY_RUN;


-- =====================================================
-- Sample Data for Testing
-- =====================================================

-- Insert sample LOB
INSERT INTO APPD_LOB_CONFIG (LOB_ID, LOB_NAME, LOB_DESCRIPTION, APPLICATION_NAMES, IS_ACTIVE)
VALUES (APPD_LOB_CONFIG_SEQ.NEXTVAL, 'Retail', 'Retail Line of Business', 
        '["RetailWeb", "RetailAPI", "RetailMobile"]', 'Y');

INSERT INTO APPD_LOB_CONFIG (LOB_ID, LOB_NAME, LOB_DESCRIPTION, APPLICATION_NAMES, IS_ACTIVE)
VALUES (APPD_LOB_CONFIG_SEQ.NEXTVAL, 'Banking', 'Banking Line of Business', 
        '["BankingWeb", "BankingCore", "BankingMobile"]', 'Y');

COMMIT;


-- =====================================================
-- Cleanup Procedure (for maintenance)
-- =====================================================
CREATE OR REPLACE PROCEDURE CLEANUP_OLD_METRICS(
    p_days_to_keep IN NUMBER DEFAULT 90
) AS
BEGIN
    -- Delete old server metrics
    DELETE FROM APPD_SERVER_METRICS 
    WHERE COLLECTION_TIME < SYSDATE - p_days_to_keep;
    
    -- Delete old JVM metrics
    DELETE FROM APPD_JVM_METRICS 
    WHERE COLLECTION_TIME < SYSDATE - p_days_to_keep;
    
    -- Delete old application metrics
    DELETE FROM APPD_APPLICATION_METRICS 
    WHERE COLLECTION_TIME < SYSDATE - p_days_to_keep;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Cleanup completed. Deleted metrics older than ' || p_days_to_keep || ' days.');
END;
/